services:
  streamlit-app:
    image: sea-assignment/streamlit-app:latest
    build:
      context: .
      dockerfile: docker/dockerfile
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    networks:
      - sea-network

networks:
  sea-network:
    driver: bridge