# Default PSO Parameters
DEFAULT_NUM_PARTICLES = 30
DEFAULT_MAX_ITERATIONS = 50
DEFAULT_INERTIA = 0.7
DEFAULT_C1 = 1.5
DEFAULT_C2 = 1.2
DEFAULT_GLOBAL_COEFF = 1.2
DEFAULT_NEIGHBOR_COUNT = 5
DEFAULT_PENALTY_FACTOR = 0.75
DEFAULT_SELECTION_THRESHOLD = 0.5

# Random Forest defaults
DEFAULT_RF_ESTIMATORS = 120
DEFAULT_RF_MAX_DEPTH = 15
DEFAULT_RF_RANDOM_STATE = 42
DEFAULT_RF_WARM_START = True
DEFAULT_RF_INCREMENTAL = True
DEFAULT_RF_INCREMENTAL_STEP = 40
